### PR TITLE
Updated build.sbt with latest versions

### PR DESCRIPTION
**Pull request by phelps-sg**

### CODE REVIEW

**Review by reyronald — APPROVED** [review]
Every version of `slick-migration-api` under 0.8.0 is not available anymore after bintray's shutdown, which means that no project using this library can compile.

@lastland Can we get this merged and released? Would solve the issue.

If anyone knows of a workaround I'll happily listen.

**Comment by lastland** [comment]
@reyronald Merged!

**Comment by reyronald** [comment]
> @reyronald Merged!

Wow great! Was honestly not expecting a response. Thanks :)

Will this be released as a new version and pushed to the registry so I can update my project?

**Comment by lastland** [comment]
I can try to see if I can update it this week---I might need some time to reconfigure everything on my side.

Thanks for being interested in this project, but I have to say that I will not have the time to maintain this project in the long run. If anyone is interested in keeping this maintained instead, that would be great :)

**Pull request merged**
