### PR TITLE
Copy the migration file instead of creating a symbolic link

### LINKED ISSUE #31: Packaging up migrations
Hi there.

We've been working to add forklift to a fairly new project recently, and for the most part it's been going well enough. I worked around the scala binary incompatibility by building my own JARs and making them available in the class path.

However, I'm now running into a new problem: we intend to ship our project in a docker container using `sbt-native-packager`, and we're discovering that (at least to my fairly-new-to-the-java-ecosystem understanding) this entire concept is incompatible with Forklift.  Symlinks with absolute paths combined with the Summary object have been rather difficult obstacles for me to overcome.

Have you encountered this, or do you have any insight into how one can package up the code such that we'd be able to bundle up the migrations and run them against our production databases?  For what it's worth, running the migrations against the production database from a local machine is not an option.

Thanks very much for your help.  I'd be glad to answer any further questions to the best of my ability.

### PR DESCRIPTION
**Pull request by softinio**
This PR should fix #31 and #28 

It is better to copy the migration file over than to create a symbolic link as migrations may be generated in one place but used and deployed elsewhere.

The link path when I generated the migration on my laptop got saved to source control with my laptop home directory in its path. This is wrong of course.

### CODE REVIEW

**Comment by lastland** [comment]
Hi @softinio, thanks for the contribution!

> It is better to copy the migration file over than to create a symbolic link as migrations may be generated in one place but used and deployed elsewhere.

In the meantime, symbolic links have the advantage that if you decide to change the migration file during development, you can do that on the linked file and your editor should usually be able to make changes to the actual file (that's at least true for Emacs).

Probably a better idea is to have two options for users to choose from? What do you think?

**Comment by softinio** [comment]
@lastland giving user choice is a good idea. Will  work on that.

**Comment by softinio** [comment]
@lastland Change to make symbolic link or copying migration an option for the user. Over to you to review. Thanks.

**Comment by softinio** [comment]
wait I made a mistake

**Comment by softinio** [comment]
@lastland can you take a look ? Thanks.

**Comment by lastland** [comment]
@softinio Thank you! I'm working on something else right now. I will take a look at it tonight!

**Comment by softinio** [comment]
@lastland ok no problem. Is there anything to setup to run tests?

**Comment by lastland** [comment]
I think you would need setup databases in addition to the usual Scala and sbt environment. If you want to run the tests, just run `sbt test` and see which tests fail. And if the failed tests are related to a particular database, you probably haven't set it up correctly.

I don't remember why the CI for PR is not working...

**Comment by lastland** [comment]
Oh, I forgot to mention that you need to `publishLocal` before running the tests because the tests actually run sbt on an example project which depends on the library, and it will only find the latest library if you do `publishLocal`. The complete command can be found in the CI configuration: https://github.com/lastland/scala-forklift/blob/develop/circle.yml

**Comment by lastland** [comment]
This looks good to me. Thanks again for the contribution!

**Comment by softinio** [comment]
@lastland your welcome. Glad I helped. Quick question when are you likely to publish this to maven as a new version to 0.3.0 ?

**Comment by lastland** [comment]
@softinio Oh thanks for reminding me of that! I should do that very soon.

**Comment by lastland** [comment]
@softinio I have released v0.3.1, but it may take a few hours to be present at Maven Central.

**Comment by smedberg** [comment]
@lastland Hey, do you intend to release a version of v0.3.1 (with this fix) which is compatible with Scala 2.11? The "[how to](https://github.com/lastland/scala-forklift#how-to-use)" seems to say that if you're on Scala 2.11 and Slick 3.2, you should use Forklift 0.2.2.  Thanks!

**Comment by lastland** [comment]
@smedberg Hi, I didn't release v0.3.1 with Scala 2.11 because I haven't done a thorough testing on Scala 2.11. Now that you have asked, I will see if I can get something done tonight. :)

**Comment by smedberg** [comment]
@lastland Thank you so much!

**Comment by lastland** [comment]
I should also document this change in README! I leave a comment here to remind myself.

**Comment by lastland** [comment]
@smedberg Published. Again, it would take some time to be present on MVN central.

**Comment by smedberg** [comment]
Thanks!

**Pull request merged**
